#!/usr/bin/ruby
# Ruby front-end for your main.
# You are free to change the language used for this script,
# but do *not* change its name.

classPath = ["bin", "lib/antlr-4.4-complete.jar"].join(":")

className = "main/WACC"
#checks that the first argument is a file, if so the java program is running in normal mode

if(ARGV.length == 1 && FileTest.file?(ARGV[0]))
    system("java -cp #{classPath} #{className} -f #{ARGV[0]}")
else
    #if flags are present, they are passed as they are to the java program
    system("java -cp #{classPath} #{className} #{ARGV.join("")}")
end
exit($?.exitstatus)
