#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.



#----------------------------------MAIN-----------------------------------------

def main
  if ARGV.empty?
    puts "Error: No Arguments given. One argument needed."
     exit -1
  end
  if ARGV[1]
    puts "Error: Too many arguments. Only One argument needed."
    exit -1
  else
  Java::Main(ARGV)
  end
end

main
